# R script for "carob"
# license: GPL (>=3)

## ISSUES
### This data is generated by a function as explained in the publication therefore is not suitable for carob 
### fertilizer rate applied is missing 
### some values of the Soil information are negative  

carob_script <- function(path) {

"
Geo-referenced crop-nutrient response function dataset for Tropical Africa

The profit potential for a given investment in fertilizer use can be estimated using representative crop nutrient response functions. Where response data is scarce, determination of representative response functions can be strengthened by using results from homologous crop growing conditions. Maize (Zea mays L.) nutrient response functions were selected from the Optimization of Fertilizer Recommendations in Africa (OFRA) database of 5500 georeferenced response functions determined from field research conducted in Sub-Saharan Africa. Three methods for defining inference domains for selection of response functions were compared. Use of the OFRA Inference Tool (OFRA-IT; http://agronomy.unl.edu/OFRA) resulted in greater specificity of maize N, P, and K response functions with higher R2 values indicating superiority compared with using the Harvest Choice Agroecological Zones (HC-AEZ) and the recommendation domains of the Global Yield Gap Atlas project (GYGA-RD). The OFRA-IT queries three soil properties in addition to climate-related properties while the latter two options use climate properties only. The OFRA-IT was generally insensitive to changes in criteria ranges of 20–25% used in queries suggesting value in using wider criteria ranges compared with the default for information scarce crop nutrient response functions.
"

	uri <- "doi:10.5061/dryad.tt6h5h1"
	group <- "Agronomy"
	ff  <- carobiner::get_data(uri, path, group)

	meta <- carobiner::get_metadata(uri, path, group, major=4, minor=NA,
		data_organization = "UNL; NARL; INRAN; RAB; IER; KALRO; IIAM; LUANAR; EIAR; ZARI; INERA; ABU; CSIR",
		publication = "doi:10.1007/s10705-017-9827-0",
		project = NA,
		carob_date = "2025-11-03",
		design = NA,
		data_type = "experiment",
		treatment_vars = "N_fertilizer;P_fertilizer; K_fertilizer",
		response_vars = "yield", 
		carob_contributor = "Cedric Ngakou",
		completion = 100,	
		notes = NA
	)
	

	f <- ff[basename(ff) == "OFRA_RespFunc_Dataset_Updated_Aug_2023.xlsx"]

	r1 <- suppressWarnings(carobiner::read.excel(f, sheet="Raw"))
	#r2 <- carobiner::read.excel(f, sheet="Notes")
	#r3 <- carobiner::read.excel(f, sheet="Map of sources")
	#r4 <- carobiner::read.excel(f, sheet="Function count")
	#r5 <- carobiner::read.excel(f, sheet="Crop List")
	
 #####  process 	

	d1 <- data.frame(
	   record_id = as.integer(1:nrow(r1)),
		trial_id = r1$Text_ID_Float...2,
		crop = r1$Crop,
		country = r1$Country...7,
		location = r1$Center...9,
		latitude = round(r1$Latitude, 3),
		longitude = round(r1$Longitude, 3),
		elevation = r1$Elevation,
		planting_date = substr(r1$Year, 1, 4),
		intercrops = ifelse(grepl("intercrop", r1$`Crop/intercrop`), r1$`Crop/intercrop`, "none"),
		variety = r1$Variety,
		previous_crop = tolower(r1$PrevCrop),
		soil_pH = rowSums(r1[, c("pH_meas...22", "pH_meas...23")]),
		soil_SOM = r1$SOM_meas,
		soil_SOC = r1$SOC_conv,
		soil_P_method = r1$`P (method)`,
		soil_P = as.numeric(gsub("<1|Trace|4to6|9to15|Olsen", NA, r1$`P ppm`)),
		soil_K_exch = r1$`Exch K`,
		soil_Ca_exch = r1$`Exch Ca`,
		soil_Mg_exch = r1$`Exch Mg`,
		soil_Na_exch = r1$`Exch Na`,
		soil_Al_exch = r1$`Exch Al`,
		soil_CEC = r1$CEC,
		soil_ECEC = r1$ECEC,
		soil_sand = r1$Sand_pct,
		soil_silt = r1$`Silt%`,
		soil_clay = r1$`Clay%`,
		soil_EC = as.numeric(gsub("n|NwP", NA, r1$EC)),
		treatment = r1$Nutrient,
		yield = (r1$CoefA -r1$CoefB*r1$CoefC)*1000,
		soil_type = r1$`Soil type`,
		on_farm = NA, 
		is_survey = FALSE, 
		yield_part = "none", 
		yield_moisture= as.numeric(NA),
		irrigated = NA, 
		geo_from_source = TRUE
		
	)

### Fixing crop names 
	
crop <- c("banana", "barley", "common bean", "cabbage", "cassava", "chickpea", "coffee", 
	  "cotton", "cowpea", "faba bean", "field pea", "finger millet", "greengrams","goundnut",
	  "potato", "lentil", "lenseed", "maize", "noug","pea", "pearl millet", "pigeon pea", "pumpkin", "rape",
	  "rice", "sesame", "sorghum", "soybean", "sunflower", "teff", "wheat", "kenaf")
d1$Num <-  match(d1$crop, unique(d1$crop))
d1$crop <- crop[d1$Num]
d1$Num <- NULL	
d1$country <- gsub("Mozamibque", "Mozambique", d1$country)
d1$country <- gsub("Zimbawe", "Zimbabwe", d1$country)	
d1$planting_date <- gsub("2104", "2014", d1$planting_date)
d1$planting_date <- gsub("??", NA, d1$planting_date)
### Fixing previous crop 
d1$previous_crop <- ifelse(grepl("beans|bean", d1$previous_crop), "common bean",
                    ifelse(grepl("sugarcane", d1$previous_crop), "sugarcane",
                    ifelse(grepl("cowpea", d1$previous_crop), "cowpea", 
                    ifelse(grepl("soybean", d1$previous_crop), "soybean", 
                    ifelse(grepl("maize", d1$previous_crop), "maize", 
                    ifelse(grepl("grass", d1$previous_crop), "grass pea", 
                    ifelse(grepl("fallow", d1$previous_crop), "none", 
                    ifelse(grepl("sunnhemp-as|dolichos-as", d1$previous_crop), "green manure", 
                    ifelse(grepl("band application of|short rains|ong rains|may|mean of 2|mid-march|december", d1$previous_crop), NA, d1$previous_crop)))))))))


d1$previous_crop <- gsub("^tef$", "teff", d1$previous_crop)

### Fixing crop 

 P <- carobiner::fix_name(d1$previous_crop)
 P <- gsub("lupine", "lupin", P)
 P <- gsub("mucuna", "velvet bean", P)
 P <- gsub("pigeonpea", "pigeon pea", P)
 P <- gsub("^rape$", "rapeseed", P)
 P <- gsub("sweet potato", "sweetpotato", P)
 d1$previous_crop <- P 
 
 P <- carobiner::fix_name(d1$crop)
 P <- gsub("field pea", "pea", P)
 P <- gsub("goundnut", "groundnut", P)
 P <- gsub("greengrams", "mung bean", P)
 P <- gsub("lenseed", "flax", P)
 P <- gsub("rape", "rapeseed", P)
 d1$crop <- P 
 

### Fixing intercrop 

P <- carobiner::fix_name(d1$intercrops)
P <- gsub(" intercrop with | intercrop ", ";", P)
d1$intercrops <- P
intercrop <- strsplit(d1$intercrops, ";")
d1$intercrops <- gsub("bean", "common bean", sapply(intercrop, `[`, 2))

### fertilizer rate applied is missing 
d1$N_fertilizer <- d1$P_fertilizer <- d1$K_fertilizer <- as.numeric(NA)


### Fixing long and lat 

i <- grepl("Eldoret", d1$location) & grepl("Kenya", d1$country)
d1$longitude[i] <- 35.267
d1$latitude[i] <- 0.5145

i <- grepl("Elgeyo Border", d1$location) & grepl("Kenya", d1$country)
d1$longitude[i] <- 35.41
d1$latitude[i] <- 0.5145

i <- grepl("Plateau du Bumbogo Buliza", d1$location) & grepl("Rwanda", d1$country)
d1$longitude[i] <- 30.059
d1$latitude[i] <- -1.8793

i <- grepl("Imbo", d1$location) & grepl("Rwanda", d1$country)
d1$longitude[i] <- 30.067
d1$latitude[i] <- -1.929

i <- grepl("Ghana", d1$country) & grepl("Adamawa Univ", d1$location)
d1$country[i] <- "Nigeria"

i <- grepl("Ghana", d1$country)
d1$longitude[i] <-  -abs(d1$longitude[i])

i <- grepl("Niger", d1$country)
d1$longitude[i] <-  abs(d1$longitude[i])


geo <- data.frame(
   location = c("Gisagara", "Rusizi", "Fashola", "Lakefront properties", "Ntechu Region","Mangochi Lakes", "Kabuku", "Nikodimos", "Gaim", "Kaptagat", "Kerita", "Moiben", "Sergoit"),
   long = c(29.843, 29.169, 3.2528, 35.058, 34.635, 35.25,38.477, 38.693, 38.752, 35.451, 35.4000, 35.376, 35.402),
   lat = c(-2.585, -2.549, 6.458, -14.2061, -14.815, -14.485 ,-5.499, 8.934, 9.0400, 0.438, 0.3303, 0.825, 0.6528),
   country = c(rep("Rwanda", 2), "Nigeria", rep("Malawi", 3), "Tanzania", rep("Ethiopia", 2), rep("Kenya", 4)),
   geo_from = TRUE
)

d1 <- merge(d1, geo, by=c("location", "country"), all.x = TRUE)

d1$longitude[!is.na(d1$long)] <- d1$long[!is.na(d1$long)]
d1$latitude[!is.na(d1$lat)] <- d1$lat[!is.na(d1$lat)]
d1$geo_from_source[!is.na(d1$geo_from)] <- d1$geo_from[!is.na(d1$geo_from)]

d1$geo_from <- d1$long <- d1$lat <- NULL

d1 <- d1[d1$yield>0, ]



carobiner::write_files(path, meta, d1)

}

